# Site settings
title: DeadBeef News
email:
description: > # this means to ignore newlines until "baseurl:"
  Get rich or die trying.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://deadbeefnews.github.io" # the base hostname & protocol for your site
twitter_username: deadbeefnews
github_username:  deadbeefnews

# Build settings
markdown: kramdown
